### ISSUE TITLE
Color profiles?

### ISSUE THREAD

**Issue by stoutbeard** [okayzed/kk.py#2]
The syntax highlighting is gorgeous, but it doesn't work very well on a light terminal background. Is there a way to change the color scheme? If there already is, maybe this should be mentioned in the readme

**Comment by okayzed** [comment]
Looking into it now! I believe it is possible, because I think I changed the colors away from the default

**Comment by okayzed** [comment]
I added instructions to the README for how to change styles. You'll need to upgrade to 0.0.39 (fresh release) for it to work. You can use pip install KitchenSink to get the new version. 

(to change styles: `export KK_STYLE=vim` for example)

**Comment by okayzed** [comment]
Let me know how that works out for you and thanks for lifting the kitchen sink!
