### ISSUE TITLE
kk doesn't always syntax highlight all git diff outputs

### ISSUE THREAD

**Issue by dylanjw** [okayzed/kk.py#4]
invocation:

```
git log | kk
```

pressing s gives the message:
Setting syntax to none. (Couldn't auto-detect syntax)

**Comment by okayzed** [comment]
Try `git log -p -n5 | kk`

(-p means print patchsets, -n5 = the most recent 5 commit)

**Comment by dylanjw** [comment]
Thanks for the quick response.

Running git log with -p, the kk does detect the syntax as "git diff".  This is maybe a separate issue, but the diff highlighting only appears for some of the commits, while the others still show the lines prepended with '-' or '+'.

**Comment by okayzed** [comment]
thats a good bug! thanks for finding it - Is it for a particular filetype (maybe a strange one?)? Or notice anything nearby the '+' that might be relevant?

**Comment by dylanjw** [comment]
The filetypes include json, python and xml.  For json, it appears to never
work.  XML sometimes works, for both the syntax and diff highlighting.  In
some xml diffs there appears "??" after the + or -, which dont appear when
viewing the diff with "less".  Python works well, when not part of a commit
that includes json or xml files.

**Comment by okayzed** [comment]
thanks, I've been investigating since yesterday and I will try to resolve it ASAP

**Comment by okayzed** [comment]
I'm not sure this addresses all issues, please re-open if it doesn't! (0.0.40)
